### ISSUE TITLE
bug: need to tweak so it will be compliance 

### ISSUE THREAD

**Issue by madtomic** [einTosti/RainbowArmor#1]
When ra is toggled. The player would get the leather armor defense bonus.

A naked player can use this perk and be wearing full set of leather armor. which is not compliance.

However, if it is limited to a world where combat is not allowed. It can be a visual perk.

**Comment by thomasmny** [comment]
So you want the option to add worlds where /ra is disabled?

**Comment by madtomic** [comment]
That would do.

**Comment by thomasmny** [comment]
Added! Is that the way you wanted it?

**Comment by thomasmny** [comment]
If it wasn't the way you wanted it, please send me a message. Otherwise #closed

**Comment by madtomic** [comment]
Thank you. This change will do. Sorry. I had been busy.
